### ISSUE TITLE
Unhandled promise rejection on seed

### ISSUE THREAD

**Issue by KhushrajRathod** [mtthwn/typebeast#150]
Hi, seeding results in an unhandled promise rejection

```
 ~/Code/typebeast/typeserver - master - npm run seed
> typeserver@0.0.0 seed /Users/khushrajrathod/Code/typebeast/typeserver
> node ./db/seed

(node:15851) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-deprecation ...` to show where the warning was created)
connection error: MongoNetworkError: failed to connect to server [cluster0-shard-00-01-9hhsv.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-01-9hhsv.mongodb.net:27017 closed
    at TLSSocket.<anonymous> (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connection.js:372:9)
    at Object.onceWrapper (events.js:421:26)
    at TLSSocket.emit (events.js:314:20)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:564:7)]
    at Pool.<anonymous> (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:314:20)
    at /Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/pool.js:1009:9
    at callback (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:97:5)
    at /Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:124:7
    at _callback (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:349:5)
    at Connection.errorHandler (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:365:5)
    at Object.onceWrapper (events.js:421:26)
    at Connection.emit (events.js:314:20)
    at TLSSocket.<anonymous> (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connection.js:370:12)
    at Object.onceWrapper (events.js:421:26)
    at TLSSocket.emit (events.js:314:20)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:564:7)
(node:15851) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [cluster0-shard-00-01-9hhsv.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-01-9hhsv.mongodb.net:27017 closed
    at TLSSocket.<anonymous> (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connection.js:372:9)
    at Object.onceWrapper (events.js:421:26)
    at TLSSocket.emit (events.js:314:20)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:564:7)]
    at Pool.<anonymous> (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:314:20)
    at /Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/pool.js:1009:9
    at callback (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:97:5)
    at /Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:124:7
    at _callback (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:349:5)
    at Connection.errorHandler (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connect.js:365:5)
    at Object.onceWrapper (events.js:421:26)
    at Connection.emit (events.js:314:20)
    at TLSSocket.<anonymous> (/Users/khushrajrathod/Code/typebeast/typeserver/node_modules/mongodb/lib/core/connection/connection.js:370:12)
    at Object.onceWrapper (events.js:421:26)
    at TLSSocket.emit (events.js:314:20)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:564:7)
(node:15851) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15851) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mtthwn** [comment]
Hi Khushraj - the issue stems from the app trying to access a cloud database cluster that doesn't exist anymore. We haven't worked on TypeBeast in quite a while, but you could probably fix this issue by connecting the app to a local mongoDB process on your machine.
